/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as InstallationImport } from "./routes/installation";
import { Route as ApplicationImport } from "./routes/application";
import { Route as AdminImport } from "./routes/admin";
import { Route as IndexImport } from "./routes/index";
import { Route as testsInstallationTestImport } from "./routes/__tests__/installation.test";

// Create/Update Routes

const InstallationRoute = InstallationImport.update({
  id: "/installation",
  path: "/installation",
  getParentRoute: () => rootRoute
} as any);

const ApplicationRoute = ApplicationImport.update({
  id: "/application",
  path: "/application",
  getParentRoute: () => rootRoute
} as any);

const AdminRoute = AdminImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRoute
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute
} as any);

const testsInstallationTestRoute = testsInstallationTestImport.update({
  id: "/__tests__/installation/test",
  path: "/installation/test",
  getParentRoute: () => rootRoute
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminImport;
      parentRoute: typeof rootRoute;
    };
    "/application": {
      id: "/application";
      path: "/application";
      fullPath: "/application";
      preLoaderRoute: typeof ApplicationImport;
      parentRoute: typeof rootRoute;
    };
    "/installation": {
      id: "/installation";
      path: "/installation";
      fullPath: "/installation";
      preLoaderRoute: typeof InstallationImport;
      parentRoute: typeof rootRoute;
    };
    "/__tests__/installation/test": {
      id: "/__tests__/installation/test";
      path: "/installation/test";
      fullPath: "/installation/test";
      preLoaderRoute: typeof testsInstallationTestImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/application": typeof ApplicationRoute;
  "/installation": typeof InstallationRoute;
  "/installation/test": typeof testsInstallationTestRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/application": typeof ApplicationRoute;
  "/installation": typeof InstallationRoute;
  "/installation/test": typeof testsInstallationTestRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/application": typeof ApplicationRoute;
  "/installation": typeof InstallationRoute;
  "/__tests__/installation/test": typeof testsInstallationTestRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/admin" | "/application" | "/installation" | "/installation/test";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/admin" | "/application" | "/installation" | "/installation/test";
  id: "__root__" | "/" | "/admin" | "/application" | "/installation" | "/__tests__/installation/test";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminRoute: typeof AdminRoute;
  ApplicationRoute: typeof ApplicationRoute;
  InstallationRoute: typeof InstallationRoute;
  testsInstallationTestRoute: typeof testsInstallationTestRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplicationRoute: ApplicationRoute,
  InstallationRoute: InstallationRoute,
  testsInstallationTestRoute: testsInstallationTestRoute
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/application",
        "/installation",
        "/__tests__/installation/test"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/application": {
      "filePath": "application.tsx"
    },
    "/installation": {
      "filePath": "installation.tsx"
    },
    "/__tests__/installation/test": {
      "filePath": "__tests__/installation.test.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
